name: frac
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^4.0.0
