name: frac
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '^3.0.0'

dependencies:
  fractal_word:
    path: ../fractal_word

dev_dependencies:
  lints: ^1.0.0
